// - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
// character_data.js
// written and released to the public domain by drow <drow@bin.sh>
// http://creativecommons.org/publicdomain/zero/1.0/

// - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
// json format
// http://en.wikipedia.org/wiki/JSON

  gen_data['main'] = [
    '{first_name}, {gender} {ethnicity} {archetype} wearing {armor} and wielding {weapon}, grew up in a {biome} {settlement}. They are motivated by {motivation}. Despite their usual {hope} nature, they feel conflicted over their {fear}.\n'
  ];
  gen_data['first_name'] = [
    'Geriya',
'Tarari',
'Mavad',
'Sahani',
'Brava',
'Pahus',
'Svenya',
'Elerir',
'Everi',
'Mane',
'Ere',
'Soufar',
'Sikari',
'Silmbe',
'Anari',
'Oriy',
'Kinane',
'Torda',
'Bannin',
'Sharsh',
'Danor',
'Taren',
'Kingoria',
'Olamu',
'Hanggest',
'Marend',
'Ralin',
'Siad',
'Midangek',
'Miland',
'Shtori',
'Mangn',
'Roruri',
'Esili',
'Jenen',
'Luma',
'Raili',
'Madet',
'Nassr',
'Zhtell',
'Nangor',
'Gusreana',
'Sarich',
'Roniy',
'Jaha',
'Afase',
'Svalli',
'Dane',
'Gelad',
'Zhdiyaja',
'Banuni',
'Kesin',
'Menen',
'Aryas',
'Shidal',
'Nansh',
'Kaniya',
'Meorya',
'Oliti',
'Olvi',
'Kasada',
'Lirile',
'Kjkane',
'Nereo',
'Czmub',
'Alat',
'Gari',
'Bjarined',
'Bagaf',
'Sanas',
'Siunn',
'Syad',
'Sinan',
'Hasan',
'Soneri',
'Menynd',
'Kerina',
'Frishade',
'Liliah',
'Alasha',
'Basa',
'Arian',
'Yulo',
'Erarin',
'Jarina',
'Kang',
'Andar',
'Atiari',
'Mide',
'Ekan',
'Halda',
'Nisar',
'Mijo',
'Dahon',
'Meetara',
'Sindang',
'Kriri',
'Ildak',
'Vinash',
'Shani',
'Sorine',
'Sastti',
'Keria',
'Ken',
'Marlori',
'Siyai',
'Surlan',
'Asmiu',
'Smodri',
'Mari',
'Eitiy',
'Jonend',
'Merasl',
'Sanda',
'Aliyara',
'Viara',
'Almbb',
'Kahda',
'Nikone',
'Lihas',
'Brkk',
'Soke',
'Sananf',
'Dalarina',
'Gusyas',
'Krar',
'Kaggw',
'Narin',
'Ilins',
'Mabink',
'Shl',
'Mava',
'Binari',
'Bring',
'Skorle',
'Store',
'Kikko',
'Andat',
'Dalito',
'Sokeh',
'Amivah',
'Saras',
'Eidara',
'Svil',
'Chanda',
'Arid',
'Yeram',
'Zaran',
'Gelan',
'Tajali',
'Gurer',
'Dangdori',
'Manar',
'Siasm',
'Sant',
'Sina',
'Awisan',
'Krvel',
'Pash',
'Yuli',
'Karas',
'Narire',
'Milennya',
'Mavann',
'Kashtte',
'Scha',
'Toldar',
'Kllarn',
'Agvar',
'Karili',
'Tharkh',
'Nage',
'Sarail',
'Annda',
'Alab',
'Elist',
'Geltor',
'Sinendo',
'Sharit',
'Siyado',
'Afyra',
'Turi',
'Manda',
'Friza',
'Pariyo',
'Enan',
'Tileri',
'Ebes',
'Souttana',
'Mareg',
'Evelest',
'Voti',
'Egasri',
'Rans',
'Zikor',
'Nani',
'Arin',
'Vama',
'Kanen',
'Olilfya',
'Stanfin',
'Bar',
'Ilarina',
'Datori',
'Lori',
'Zanin',
'Tina',
'Kanont',
'Czhoryar',
'Dan',
'Ari',
'Erefior',
'Kages',
'Datid',
'Kaninah',
'Gart',
'Gena',
'Krik',
'Deynexi',
'Liboryar',
'Geomikok',
'Nahawd',
'Marias',
'Sontir',
'Aishor',
'Hasaru',
'Lire',
'Salyay',
'Likh',
'Mickya',
'Orera',
'Vonri',
'Ashane',
'Geni',
'Arilen',
'Nera',
'Jatigie',
'Ileeha',
'Jerare',
'Vinn',
'Vadsh',
'Lorne',
'Oler',
'Tarna',
'Maner',
'Jashar',
'Kiyanin',
'Tanya',
'Jeni'
  ];
  gen_data['biome'] = [
    'taiga',
    'desert',
    'woodland',
    'coastal',
    'jungle',
    'swamp',
    'bog',
    'grassland',
    'outlying',
    'remote',
    'canyon',
    'fringe',
    'wealthy',
    'wasteland',
    'plateau',
    'tundra',
    'icy',
    'humid',
    'mountainous',
    'archipelago',
    'oasis',
    'abandoned',
    'celestial',
    'infernal',
    'planar',
    'coral'
  ];
  gen_data['settlement'] = [
    'thorp',
    'keep',
    'monastery',
    'village',
    'hamlet',
    'town',
    'city',
    'capital',
    'port',
    'cave',
    'temple',
    'farm',
    'homestead',
    'villa',
    'valley',
    'ruin',
    'druid circle',
    'prison'
  ];
  gen_data['gender'] = [
    'cismale',
    'cisfemale',
    'non-binary',
    'intersex',
    'transmale',
    'transfemale',
    'construct'
  ];
gen_data['ethnicity'] = {
'1-99':	'human',
'100-150':	'gold dwarf',
'151-160':	'gray dwarf',
'161-199':	'shield dwarf',
'200-215':	'drow',
'215-235':	'moon elf',
'236-255':	'sun elf',
'256-275':	'wood elf',
'275-285':	'sea elf',
'286-290':	'mountain elf',
'291-299':	'desert elf',
'300-315':	'deep gnome',
'316-355':	'rock gnome',
'356-399':	'halfling',
'400-415':	'planetouched',
'416-449':	'orc',
'450':	'{ethnicity} and {ethnicity}'
  };
  gen_data['archetype'] = {
'1':  'animal/monster handler',
'2':  'arborist',
'3':  'baler',
'4':  'beekeeper',
'5':  'breeder',
'6':  'cowherd',
'7':  'dairyboy/dairymaid',
'8':  'falconer',
'9':  'farmer',
'10':   'fisher',
'11':   'florist',
'12':   'forager',
'13':   'forester',
'14':   'fowler',
'15':   'gamekeeper',
'16':   'groom',
'17':   'herder',
'18':   'horse trainer',
'19':   'hunter',
'20':   'lumberjack',
'21':   'horse trainer',
'22':   'hound trainer',
'23':   'miller',
'24':   'miner',
'25':   'pathfinder',
'26':   'plumer',
'27':   'prospector',
'28':   'ranger',
'29':   'renderer',
'30':   'shepherd',
'31':   'stablehand',
'32':   'thresher',
'33':   'trapper',
'34':   'vintner',
'35':   'zookeeper',
'36':   'architect',
'37':   'brickmaker',
'38':   'brickmason',
'39':   'carpenter',
'40':   'construction worker',
'41':   'general contractor',
'42':   'glazier',
'43':   'plasterer',
'44':   'roadlayer/streetlayer',
'45':   'roofer/thatcher',
'46':   'stonemason',
'47':   'acrobat',
'48':   'actor',
'49':   'aerialist/trapezist',
'50':   'arranger',
'51':   'athlete',
'52':   'busker/street musician',
'53':   'celebrity',
'54':   'chef',
'55':   'choir trainer',
'56':   'clown',
'57':   'comedian',
'58':   'conductor',
'59':   'contortionist',
'60':   'curator',
'61':   'costumer',
'62':   'dancer',
'63':   'equilibrist',
'64':   'fashion designer',
'65':   'gladiator',
'66':   'glasspainter',
'67':   'jester',
'68':   'juggler',
'69':   'illuminator',
'70':   'limner',
'71':   'makeup artist',
'72':   'minstrel',
'73':   'model',
'74':   'musician',
'75':   'painter',
'76':   'playwright',
'77':   'poet',
'78':   'ringleader',
'79':   'ropewalker',
'80':   'sculptor',
'81':   'singer/soprano',
'82':   'skald',
'83':   'stage magician',
'84':   'tumbler',
'85':   'tattooist',
'86':   'theater director',
'87':   'wrestler',
'88':   'writer',
'89':   'accountant',
'90':   'actuary',
'91':   'animal collector/monster collector',
'92':   'business owner',
'93':   'debt collector',
'94':   'draper',
'95':   'appraiser',
'96':   'auctioneer',
'97':   'banker',
'98':   'bagniokeeper',
'99':   'bookkeeper',
'100':  'chandler',
'101':  'collector',
'102':  'entrepreneur',
'103':  'grocer',
'104':  'guild leader',
'105':  'innkeeper',
'106':  'land surveyor',
'107':  'merchant',
'108':  'moneychanger',
'109':  'moneylender',
'110':  'peddler',
'111':  'pimp/madame',
'112':  'plantation owner',
'113':  'speculator',
'114':  'thriftdealer',
'115':  'tradesperson',
'116':  'vendor',
'117':  'billboardposter',
'118':  'courier',
'119':  'herald',
'120':  'interpreter',
'121':  'linguist',
'122':  'messenger',
'123':  'town crier',
'124':  'translator',
'125':  'accoutrementer/coinsmith',
'126':  'armorer',
'127':  'blacksmith',
'128':  'bladesmith',
'129':  'bookbinder',
'130':  'bottler',
'131':  'bowyer',
'132':  'brewer',
'133':  'broom maker',
'134':  'candlemaker',
'135':  'cartwright',
'136':  'cobbler',
'137':  'cooper/hooper',
'138':  'cutler',
'139':  'dyer',
'140':  'embroiderer',
'141':  'engraver',
'142':  'farrier',
'143':  'fletcher',
'144':  'furniture artisan',
'145':  'furrier',
'146':  'glassworker',
'147':  'glovemaker',
'148':  'goldsmith/silversmith',
'149':  'hatter/milliner',
'150':  'instrument maker',
'151':  'lapidary',
'152':  'leatherworker',
'153':  'jeweler',
'154':  'locksmith',
'155':  'luthier',
'156':  'mercer',
'157':  'optician',
'158':  'potter',
'159':  'printer',
'160':  'restorer',
'161':  'ropemaker',
'162':  'rugmaker',
'163':  'saddler',
'164':  'seamstress/tailor',
'165':  'soaper',
'166':  'tanner',
'167':  'taxidermist',
'168':  'tinker',
'169':  'toymaker',
'170':  'watchmaker',
'171':  'weaponsmith',
'172':  'weaver',
'173':  'wheelwright',
'174':  'whittler/woodcarver',
'175':  'assassin',
'176':  'bandit ',
'177':  'burglar',
'178':  'charlatan',
'179':  'gamefighter',
'180':  'crime boss',
'181':  'cutpurse',
'182':  'drug dealer',
'183':  'drug lord',
'184':  'extortioner',
'185':  'fence',
'186':  'forger',
'187':  'fugitive',
'188':  'highway robber',
'189':  'kidnapper',
'190':  'loan shark',
'191':  'pirate',
'192':  'poacher',
'193':  'poisoner',
'194':  'raider/marauder',
'195':  'smuggler',
'196':  'thief',
'197':  'affeeror',
'198':  'agister',
'199':  'alderperson',
'200':  'alienist',
'201':  'assayer',
'202':  'baron/baroness',
'203':  'chancellor',
'204':  'chief',
'205':  'conservationist',
'206':  'count/earl/countess',
'207':  'courtier',
'208':  'diplomat',
'209':  'duke/duchess',
'210':  'emperor/empress',
'211':  'judge',
'212':  'king/queen',
'213':  'knight',
'214':  'lady-in-waiting',
'215':  'lawyer/advocate',
'216':  'marquess/marchioness',
'217':  'treasurer',
'218':  'revel-leader',
'219':  'minister',
'220':  'noble/aristocrat',
'221':  'notary',
'222':  'orator/spokesperson',
'223':  'page',
'224':  'prince/princess',
'225':  'senator',
'226':  'sheriff',
'227':  'spy chief',
'228':  'steward',
'229':  'squire',
'230':  'tax collector',
'231':  'viscount/viscountess',
'232':  'ward',
'233':  'acater',
'234':  'tunner',
'235':  'baker',
'236':  'barber',
'237':  'barkeep',
'238':  'barmaid/barboy',
'239':  'butcher',
'240':  'butler',
'241':  'caregiver',
'242':  'charcoal maker',
'243':  'chatelaine/majordomo',
'244':  'chimney sweeper',
'245':  'clerk',
'246':  'cook',
'247':  'copyist',
'248':  'croupier',
'249':  'exterminator',
'250':  'food & drink taster',
'251':  'gardener/landscaper',
'252':  'gongfarmer',
'253':  'gravedigger',
'254':  'groundskeeper',
'255':  'kitchen drudge',
'256':  'knacker',
'257':  'lamplighter',
'258':  'laundry worker',
'259':  'lector',
'260':  'longshore worker',
'261':  'maid',
'262':  'nanny/nursemaid',
'263':  'operator',
'264':  'pastry chef',
'265':  'plumber',
'266':  'porter',
'267':  'courtesan',
'268':  'quarryperson',
'269':  'servant',
'270':  'stagehand',
'271':  'street cleaner',
'272':  'talent scout',
'273':  'trainer',
'274':  'water bearer',
'275':  'wet nurse',
'276':  'abjurer',
'277':  'alchemist',
'278':  'archmage',
'279':  'artificer',
'280':  'bard',
'281':  'conjuror',
'282':  'druid',
'283':  'elementalist',
'284':  'enchanter/enchantress',
'285':  'evoker',
'286':  'healer',
'287':  'hearth witch/hearth wizard',
'288':  'illusionist',
'289':  'mage',
'290':  'medium',
'291':  'meteorologist',
'292':  'necromancer',
'293':  'ritualist',
'294':  'runecaster',
'295':  'sage',
'296':  'seer/oracle',
'297':  'animist',
'298':  'shapeshifter',
'299':  'sorcerer/sorceress',
'300':  'summoner',
'301':  'transmuter',
'302':  'warlock',
'303':  'witchdoctor',
'304':  'witch',
'305':  'wizard',
'306':  'wordsmith',
'307':  'admiral',
'308':  'bailiff',
'309':  'bodyguard',
'310':  'bouncer',
'311':  'captain',
'312':  'castellan',
'313':  'cavalier',
'314':  'city watch',
'315':  'commissar',
'316':  'constable',
'317':  'detective/investigator',
'318':  'drummer/fifer',
'319':  'duelist',
'320':  'executioner',
'321':  'firefighter',
'322':  'guard/sentinel',
'323':  'general',
'324':  'inspection officer',
'325':  'intelligence officer',
'326':  'jailer',
'327':  'lieutenant',
'328':  'archer',
'329':  'marshall',
'330':  'medic',
'331':  'mercenary',
'332':  'privateer',
'333':  'supply chief',
'334':  'royal guard',
'335':  'runner',
'336':  'sapper',
'337':  'sergeant',
'338':  'sergeant-at-arms',
'339':  'scout',
'340':  'siege artillerist',
'341':  'slave driver',
'342':  'soldier',
'343':  'special force soldier',
'344':  'spy',
'345':  'tactician',
'346':  'tollkeeper',
'347':  'torturer',
'348':  'warden',
'349':  'warmage',
'350':  'abbot/abbess',
'351':  'acolyte',
'352':  'almoner',
'353':  'archbishop',
'354':  'bishop',
'355':  'cantor',
'356':  'cardinal',
'357':  'chaplain',
'358':  'cleric of {faerun_gods}',
'359':  'confessor',
'360':  'cultist of {faerun_gods}',
'361':  'cult leader',
'362':  'deacon',
'363':  'diviner',
'364':  'exorcist',
'365':  'high priest of {faerun_gods}',
'366':  'inquisitor',
'367':  'missionary of {faerun_gods}',
'368':  'monk',
'369':  'nun',
'370':  'paladin of {faerun_gods}',
'371':  'pardoner',
'372':  'priest/priestess of {faerun_gods}',
'373':  'prophet',
'374':  'sexton',
'375':  'templar',
'376':  'abecedarian',
'377':  'accoucheur/obstetrician/midwife',
'378':  'anthropologist',
'379':  'apothecary',
'380':  'apprentice',
'381':  'archaeologist',
'382':  'archivist',
'383':  'assayer',
'384':  'astrologer',
'385':  'astronomer',
'386':  'bloodletter',
'387':  'botanist',
'388':  'cartographer',
'389':  'chemist',
'390':  'dean',
'391':  'doctor/physician',
'392':  'drakologist',
'393':  'engineer',
'394':  'entomologist',
'395':  'herbalist',
'396':  'historian',
'397':  'horologist',
'398':  'librarian',
'399':  'mathematician',
'400':  'mortician',
'401':  'nurse',
'402':  'optometrist',
'403':  'philosopher',
'404':  'professor',
'405':  'scholar/researcher',
'406':  'scribe',
'407':  'student',
'408':  'surgeon/chirurgeon',
'409':  'taxonomist',
'410':  'teacher',
'411':  'theologian',
'412':  'tutor',
'413':  'veterinarian',
'414':  'zoologist',
'415':  'navigator',
'416':  'bosun',
'417':  'cabbie/wagoner',
'418':  'cabin boy/cabin girl',
'419':  'caravaneer',
'420':  'charioteer',
'421':  'carter',
'422':  'ferryperson',
'423':  'first mate',
'424':  'helmsperson',
'425':  'navigator',
'426':  'purser',
'427':  'sailor',
'428':  'sea captain',
'429':  'shipwright',
'430':  'adventurer',
'431':  'beggar/pauper',
'432':  'blood hunter/monster hunter',
'433':  'bounty hunter',
'434':  'crossing sweeper',
'435':  'deserter',
'436':  'disgraced noble',
'437':  'drunkard',
'438':  'dungeon delver',
'439':  'elder',
'440':  'exile',
'441':  'explorer',
'442':  'ex',
'443':  'folk hero',
'444':  'gambler',
'445':  'grave robber/tomb raider',
'446':  'heretic',
'447':  'hermit',
'448':  'housewife/househusband',
'449':  'pilgrim',
'450':  'prisoner',
'451':  'rag',
'452':  'rebel/political dissident',
'453':  'refugee',
'454':  'runaway slave',
'455':  'scavenger/mudlark/tosher',
'456':  'slave',
'457':  'squatter',
'458':  'traveler/wanderer/vagabond',
'459':  'urchin'
  };
  gen_data['armor'] = {
    '01-15': 'plain clothes',
    '16-20': 'well-fit clothes',
    '21-24': 'extravagant clothes',
    '25-28': 'rags',
    '29-30': 'loin cloth',
    '31-35': 'padded armor',
    '36-45': 'robes',
    '45-55': 'leather armor',
    '56-60': 'studded leather armor',
    '61-65': 'hide armor',
    '66-71': 'chainmail',
    '72-74': 'scale mail',
    '75-79': 'breastplate',
    '80-83': 'half plate',
    '84-85': 'ring mail',
    '86-91': 'chainmail',
    '92-94': 'splint mail',
    '95-100': 'plate mail'
  };
  gen_data['weapon'] = [
    'a {one_handed_weapon}',
    'a {one_handed_weapon} and a {shield}',
    'dual {one_handed_weapon}s',
    '{two_handed_weapon}'
  ];
  gen_data['one_handed_weapon'] = [
    'blackjack', 'battleaxe', 'mace', 'short sword', 'bastard sword', 'long sword', 'club', 'morningstar', 'katana'
  ];
  gen_data['two_handed_weapon'] = [
    'a longbow', 'a pitchfork', 'a heavy crossbow', 'a light crossbow', 'a shortbow', 'a sling and bullets', 'daikatana', 'spear', 'darts', 'a javelin', 'throwing axes', 'two-handed sword', 'warhammer'
  ];
  gen_data['shield'] = [
    'buckler', 'targe', 'kite shield', 'tower shield'
  ];
  gen_data['motivation'] = {
'1':  'dominate another',
'2':  'reach spiritual enlightenment',
'3':  'avoid death',
'4':  'avoid poverty',
'5':  'cure their disease',
'6':  'develop into a leader',
'7':  'become the sole power',
'8':  'accept from others',
'9':  'appreciate friends and family',
'10':   'share their wealth',
'11':   'compete',
'12':   'tear down the old ways',
'13':   'care for an aging parent',
'14':   'continue a legacy',
'15':   'defeat an antagonist',
'16':   'cause pain to someone',
'17':   'maintain their wits',
'18':   'control others',
'19':   'manage an illness',
'20':   'overcome perceived mistakes',
'21':   'dsicover something important',
'22':   'deal with bullies',
'23':   'find themself',
'24':   'do the right thing',
'25':   'create a new identity',
'26':   'escape a life of crime and danger',
'27':   'escape murderers',
'28':   'escape confinement',
'29':   'escape danger',
'30':   'find a home',
'31':   'defeat colonizers',
'32':   'escape widespread disaster',
'33':   'evade responsibility',
'34':   'build a family, whether chosen or birth',
'35':   'find a lifelong partner',
'36':   'find friendship or companionship',
'37':   'find their calling in life',
'38':   'find something lost',
'39':   'fit in',
'40':   'create societal change',
'41':   'deepen their religious conversion',
'42':   'forge oneself',
'43':   'gain control over their own life',
'44':   'get revenge',
'45':   'abandon a child',
'46':   'have a child',
'47':   'have it all',
'48':   'help a loved one recognize they are hurting those around them',
'49':   'keep what one has no matter what',
'50':   'learn to trust again',
'51':   'make someone proud',
'52':   'find stability in changing home life',
'53':   'obliterate an enemy',
'54':   'obsess for a person or thing',
'55':   'obtain glory whatever the cost',
'56':   'survive the elements',
'57':   'find themself after abuse',
'58':   'overcome addiction',
'59':   'overcome their deepest fear',
'60':   'overcome a fear',
'61':   'defeat good with evil',
'62':   'profiteer',
'63':   'sow chaos',
'64':   'protect loved ones',
'65':   'fortify their homeland',
'66':   'provide for family',
'67':   'protect future generations',
'68':   'prove someone wrong',
'69':   'pursue their passions',
'70':   'pursue a toxic desire',
'71':   'pursue justice',
'72':   'pursue expertise in a skill',
'73':   'fulfill their a hidden dream',
'74':   'reconcile with estranged loved ones',
'75':   'repay a debt',
'76':   'rescue someone from who or what binds them',
'77':   'gain independence',
'78':   'restore their name and reputation',
'79':   'right a deep wrong',
'80':   'ruin a reputation',
'81':   'save their community',
'82':   'seek death',
'83':   'serve others',
'84':   'solve a riddle',
'85':   'stop an a prophesied event',
'86':   'support oneself financially',
'87':   'survive loss',
'88':   'survive the death of a loved one',
'89':   'take what one is owed',
'90':   'explore the unknown',
'91':   'succeed where they have failed before',
'92':   'fulfill a geas or curse',
'93':   'win a competition'
  };
  gen_data['hope'] = {
    '1':  'accessible',
    '2':  'active',
    '3':  'adaptable',
    '4':  'admirable',
    '5':  'adventurous',
    '6':  'agreeable',
    '7':  'alert',
    '8':  'allocentric',
    '9':  'amiable',
    '10':   'anticipative',
    '11':   'appreciative',
    '12':   'articulate',
    '13':   'aspiring',
    '14':   'athletic',
    '15':   'attractive',
    '16':   'balanced',
    '17':   'benevolent',
    '18':   'brilliant',
    '19':   'calm',
    '20':   'capable',
    '21':   'captivating',
    '22':   'caring',
    '23':   'challenging',
    '24':   'charismatic',
    '25':   'charming',
    '26':   'cheerful',
    '27':   'clean',
    '28':   'clear-headed',
    '29':   'clever',
    '30':   'colorful',
    '31':   'companionly',
    '32':   'compassionate',
    '33':   'conciliatory',
    '34':   'confident',
    '35':   'conscientious',
    '36':   'considerate',
    '37':   'constant',
    '38':   'contemplative',
    '39':   'cooperative',
    '40':   'courageous',
    '41':   'courteous',
    '42':   'creative',
    '43':   'cultured',
    '44':   'curious',
    '45':   'daring',
    '46':   'debonair',
    '47':   'decent',
    '48':   'decisive',
    '49':   'dedicated',
    '50':   'deep',
    '51':   'dignified',
    '52':   'directed',
    '53':   'disciplined',
    '54':   'discreet',
    '55':   'dramatic',
    '56':   'dutiful',
    '57':   'dynamic',
    '58':   'earnest',
    '59':   'ebullient',
    '60':   'educated',
    '61':   'efficient',
    '62':   'elegant',
    '63':   'eloquent',
    '64':   'empathetic',
    '65':   'energetic',
    '66':   'enthusiastic',
    '67':   'esthetic',
    '68':   'exciting',
    '69':   'extraordinary',
    '70':   'fair',
    '71':   'faithful',
    '72':   'farsighted',
    '73':   'felicific',
    '74':   'firm',
    '75':   'flexible',
    '76':   'focused',
    '77':   'forecful',
    '78':   'forgiving',
    '79':   'forthright',
    '80':   'freethinking',
    '81':   'friendly',
    '82':   'fun-loving',
    '83':   'gallant',
    '84':   'generous',
    '85':   'gentle',
    '86':   'genuine',
    '87':   'good-natured',
    '88':   'gracious',
    '89':   'hardworking',
    '90':   'healthy',
    '91':   'hearty',
    '92':   'helpful',
    '93':   'herioc',
    '94':   'high-minded',
    '95':   'honest',
    '96':   'honorable',
    '97':   'humble',
    '98':   'humorous',
    '99':   'idealistic',
    '100':  'imaginative',
    '101':  'impressive',
    '102':  'incisive',
    '103':  'incorruptible',
    '104':  'independent',
    '105':  'individualistic',
    '106':  'innovative',
    '107':  'inoffensive',
    '108':  'insightful',
    '109':  'insouciant',
    '110':  'intelligent',
    '111':  'intuitive',
    '112':  'invulnerable',
    '113':  'kind',
    '114':  'knowledge',
    '115':  'leaderly',
    '116':  'leisurely',
    '117':  'logical',
    '118':  'lovable',
    '119':  'loyal',
    '120':  'lyrical',
    '121':  'magnanimous',
    '122':  'many-sided',
    '123':  'mature',
    '124':  'methodical',
    '125':  'meticulous',
    '126':  'moderate',
    '127':  'modest',
    '128':  'multi-leveled',
    '129':  'neat',
    '130':  'nonauthoritarian',
    '131':  'objective',
    '132':  'observant',
    '133':  'open',
    '134':  'optimistic',
    '135':  'orderly',
    '136':  'organized',
    '137':  'original',
    '138':  'painstaking',
    '139':  'passionate',
    '140':  'patient',
    '141':  'patriotic',
    '142':  'peaceful',
    '143':  'perceptive',
    '144':  'perfectionist',
    '145':  'personable',
    '146':  'persuasive',
    '147':  'planful',
    '148':  'playful',
    '149':  'polished',
    '150':  'popular',
    '151':  'practical',
    '152':  'precise',
    '153':  'principled',
    '154':  'profound',
    '155':  'protean',
    '156':  'protective',
    '157':  'providential',
    '158':  'prudent',
    '159':  'punctual',
    '160':  'pruposeful',
    '161':  'rational',
    '162':  'realistic',
    '163':  'reflective',
    '164':  'relaxed',
    '165':  'reliable',
    '166':  'resourceful',
    '167':  'respectful',
    '168':  'responsible',
    '169':  'responsive',
    '170':  'reverential',
    '171':  'romantic',
    '172':  'rustic',
    '173':  'sage',
    '174':  'sane',
    '175':  'scholarly',
    '176':  'scrupulous',
    '177':  'secure',
    '178':  'selfless',
    '179':  'self-critical',
    '180':  'self-defacing',
    '181':  'self-denying',
    '182':  'self-reliant',
    '183':  'self-sufficient',
    '184':  'sensitive',
    '185':  'sentimental',
    '186':  'seraphic',
    '187':  'serious',
    '188':  'sexy',
    '189':  'sharing',
    '190':  'shrewd',
    '191':  'simple',
    '192':  'skillful',
    '193':  'sober',
    '194':  'sociable',
    '195':  'solid',
    '196':  'sophisticated',
    '197':  'spontaneous',
    '198':  'sporting',
    '199':  'stable',
    '200':  'steadfast',
    '201':  'steady',
    '202':  'stoic',
    '203':  'strong',
    '204':  'studious',
    '205':  'suave',
    '206':  'subtle',
    '207':  'sweet',
    '208':  'sympathetic',
    '209':  'systematic',
    '210':  'tasteful',
    '211':  'teacherly',
    '212':  'thorough',
    '213':  'tidy',
    '214':  'tolerant',
    '215':  'tractable',
    '216':  'trusting',
    '217':  'uncomplaining',
    '218':  'understanding',
    '219':  'undogmatic',
    '220':  'unfoolable',
    '221':  'upright',
    '222':  'urbane',
    '223':  'venturesome',
    '224':  'vivacious',
    '225':  'warm',
    '226':  'well-read',
    '227':  'well-rounded',
    '228':  'winning',
    '229':  'wise',
    '230':  'witty',
    '231':  'youthful'
  };
  gen_data['fear'] = {
    '1':  'abusive nature',
    '2':  'alcoholism',
    '3':  'addiction',
    '4':  'aimlessness',
    '5':  'anxiety',
    '6':  'arrogance',
    '7':  'audaciousness',
    '8':  'big mouth',
    '9':  'bigotry',
    '10':   'bluntness',
    '11':   'boldness',
    '12':   'callousness',
    '13':   'childishness',
    '14':   'complexity',
    '15':   'cruelty',
    '16':   'being cursed',
    '17':   'dependency',
    '18':   'derangement',
    '19':   'disloyalty',
    '20':   'disorder',
    '21':   'disturbing behavior',
    '22':   'doubtfulness',
    '23':   'dyslexia',
    '24':   'egotism',
    '25':   'enviousness',
    '26':   'erraticness',
    '27':   'fanaticism',
    '28':   'fickleness',
    '29':   'fierceness',
    '30':   'finickiness',
    '31':   'fixation',
    '32':   'filtatiousness',
    '33':   'foolishness',
    '34':   'frailty',
    '35':   'fraudulence',
    '36':   'gluttony',
    '37':   'gruffness',
    '38':   'gullibility',
    '39':   'habitualness',
    '40':   'hardness',
    '41':   'hedonism',
    '42':   'hoity-toity-ness',
    '43':   'humorlessness',
    '44':   'hypocrisy',
    '45':   'idealism',
    '46':   'idiocy',
    '47':   'ignorance',
    '48':   'illiterateness',
    '49':   'impatience',
    '50':   'impiousness',
    '51':   'incompetence',
    '52':   'indecisiveness',
    '53':   'indifference',
    '54':   'infamy',
    '55':   'intolerance',
    '56':   'immaturity',
    '57':   'impishness',
    '58':   'judgmentalness',
    '59':   'klutzy',
    '60':   'laziness',
    '61':   'lewdness',
    '62':   'lying',
    '63':   'lust',
    '64':   'masochism',
    '65':   'meddling',
    '66':   'meekness',
    '67':   'megalomania',
    '68':   'murder',
    '69':   'naivety',
    '70':   'nerves',
    '71':   'nonviolence',
    '72':   'nosiness',
    '73':   'obsessions',
    '74':   'oppressiveness',
    '75':   'over-ambition',
    '76':   'over-empathy',
    '77':   'over-protectiveness',
    '78':   'over-confidence',
    '79':   'zealotry',
    '80':   'pacifism',
    '81':   'paranoia',
    '82':   'peevishness',
    '83':   'pestering',
    '84':   'pessimism',
    '85':   'perfectionism',
    '86':   'phobia',
    '87':   'practicality',
    '88':   'precarity',
    '89':   'predictability',
    '90':   'pride',
    '91':   'rakishness',
    '92':   'rebelliousness',
    '93':   'recklessness',
    '94':   'remorselessness',
    '95':   'rigorousness',
    '96':   'sadism',
    '97':   'sarcasm',
    '98':   'sadomasochism',
    '99':   'skepticism',
    '100':  'seductiveness',
    '101':  'senility',
    '102':  'scoundrelness',
    '103':  'selfishness',
    '104':  'self-martyrdom',
    '105':  'self-righteousness',
    '106':  'shallowness',
    '107':  'smart-ass nature',
    '108':  'softness',
    '109':  'solemness',
    '110':  'spinelessness',
    '111':  'spite',
    '112':  'spoiled nature',
    '113':  'stubborness',
    '114':  'squeamishness',
    '115':  'superstitions',
    '116':  'tact',
    '117':  'temperament',
    '118':  'temptations',
    '119':  'theatricality',
    '120':  'feeling tongue-tied',
    '121':  'timidness',
    '122':  'troublesomeness',
    '123':  'perceived ugliness',
    '124':  'unluckiness',
    '125':  'untrustworthiness',
    '126':  'unpredictableness',
    '127':  'using of others',
    '128':  'vanity',
    '129':  'weakness',
    '130':  'withdrawnness',
    '131':  'dourness',
    '131':  'low self-worth',
    '132':  'depression'
  };

gen_data['faerun_region'] = [
    'Icewind Dale',
    'the Sword Coast',
    'the Silver Marches',
    'Amn',
    'Calimshan',
    'Tethyr',
    'Thindol',
    'Samarach',
    'Anauroch',
    'Cormyr',
    'Sembia',
    'Impiltur',
    'Damara',
    'Vaasa',
    'Narfell',
    'the Great Dale',
    'the Endless Wastes',
    'Thay',
    'Algarond',
    'Altumbel',
    'Mulhorand',
    'Unther',
    'Chessenta',
    'Chondath',
    'the Shar',
    'Halruaa',
    'Lapaliiya',
    'Dambrath',
    'Estagund',
    'Dambrath',
    'Durpar',
    'Lantan',
    'the Moonshae Isles',
    'the Pirate Isles',
    'Murghom'
];

gen_data['faerun_cities'] = [
    'Waterdeep',
    'Luskan',
    'Neverwinter',
    'Mirabar',
    'Longsaddle',
    'Yartar',
    'Triboar',
    'Red Larch',
    'Daggerford',
    'Nesme',
    'Silverymoon',
    'Everlund',
    'Sundabar',
    'Ascore',
    'Mothral Hall',
    'Griffon\'s Nest'
];

gen_data['faerun_organization'] = {
	'01':	'Harper\s',
	'02':	'Order of the Gaunlet',
	'03':	'Emerald Enclave',
	'04':	'Lords\' Alliance',
	'05':	'Zhentarim',
	'06-15':	'{faerun_gods}'
};

gen_data['faerun_gods'] = [
    'Arvandor',
    'Corellon Larethian',
    'Banehold',
    'Bane',
    'Celestia',
    'Torm',
    'The Deep Wilds',
    'Silvanus',
    'The Demonweb Pits',
    'Lolth',
    'The Dismal Caverns',
    'Ghaunadaur',
    'Dwarfhome',
    'Moradin',
    'Eternal Sun',
    'Amaunator',
    'The Fugue Plane',
    'Kelemvor',
    'Gates of the Moon',
    'Selune',
    'Sune',
    'Green Fields',
    'Chauntea',
    'House of Knowledge',
    'The Nine Hells',
    'Asmodeus',
    'Nishrek',
    'Gruumsh',
    'The Supreme Throne',
    'Cyric',
    'Towers of the Night',
    'Shar',
    'Warrior\'s Rest',
    'Tempus',
    'Akadi',
    'Grumbar', 
    'Kossuth',
    'Istishia',
    'Annam All-Father',
    'Memnor',
    'Grolantor',
    'Skoraeus Stonebones',
    'Surtr',
    'Thrym'
];


gen_data['plots'] = [
	'{dream_plot}',
	'{distress_plot}',
	'{treasure_plot}',
	'{crime_plot}',
	'{vignette_plot}',
	'{political_plot}'
];


gen_data['dream_plot'] = [
	'Dreaming, you find yourself in a {biome} {settlement}, a {descriptor} {tarot_arcana} rests {direction}.',
	'As your eyes close, you see a {archetype} holding {object}. You sense that they seek to {motivation}.',
	'You wake in a cold sweat. Feelings of {fear} cloud your mind.',
	'An image of {faerun_gods} appears. It commands you to {motivation} in {faerun_region}.'
];

gen_data['distress_plot'] = [
	'A {archetype}\'s {relationships} has gone missing. The only clue is the closest {biome} {settlement}.',
	'In town, an {archetype} hands you a {short_document} from a {settlement} outside {faerun_cities}. A {archetype} {distress_type} a {crime_type}.'
];

gen_data['treasure_plot'] = [
	'Go to the {biome} {settlement}. Head {cardinal_directions} by {number} {units}. Look for {object}.',
	'{admonition} a {tarot_arcana}. They will know whether to head {cardinal_directions}.'
];

gen_data['crime_plot'] = [
	'A criminal offers you work on their last {crime_type}. This job is in {faerun_cities}. Your target is a {archetype} with ties to {faerun_organization}.',
	'A {noise} around {time_of_day}. Locals say a {crime_type} has taken place in a nearby {settlement}.',
	'This is no ordinary {crime_type}. The target is surprisingly {hope} with an intense desire to {motivation}.'
];

gen_data['vignette_plot'] = [
	'Once upon a time...',
	'Under an overwhelming sense of {fear}, ...'
];

gen_data['political_plot'] = [
	'A {political_conflict} between {faerun_region} and {faerun_region}.',
	'A {settlement} in {faerun_region} begs for aid as a {political_conflict}.'
];

gen_data['political_conflict'] = [
	'war breaks out',
	'trade dispute develops',
	'illegitimate {cultural_adjective} ruler vies for power',
	'game of ravens foments',
	'famine develops',
	'arcane disaster hits',
	'tournament begins',
	'meteor lands',
	'disputed claim to succession',
	'{cultural_adjective} {military_unit} {military_verb}',
	'cult of {faerun_gods} emerges',
	'herectic of {faerun_gods} damages the faith',
	'economic calamity hits',
	'a ruler\'s {crime_type} threatens a diplomatic incident'
];

gen_data['distress_type'] = [
	'seeks aid after',
	'plots',
	'prepares against',
	'witnessed'
];

gen_data['noise'] = [
	'scream rings out',
	'commotion develops',
	'scene forms',
	'yell echoes'
];

gen_data['crime_type'] = [
	'theft',
	'assassination',
	'counterfeit',
	'insurrection',
	'con',
	'heist',
	'murder',
	'kidnapping',
	'ransom',
	'extortion'
];

gen_data['cultural_adjective'] = [
	'elven',
	'undead',
	'illithid',
	'dwarven',
	'human',
	'goblin',
	'orc',
	'gnomish',
	'planar'
]


gen_data['military_unit'] = [
	'army',
	'battalion',
	'armada',
	'horde',
	'siege force',
	'division'
]

gen_data['military_verb'] = [
	'marshalls',
	'musters',
	'recruits',
	'forms',
	'stages itself',
	'sets camp'
]

gen_data['admonition'] = [
	'Beware',
	'Mind',
	'Fear',
	'Follow',
	'Worship'
]

gen_data['time_of_day'] = [
	'midnight',
	'evening',
	'high noon',
	'morning',
	'sunset',
	'sunrise'
]

gen_data['relationships'] = [
	'child',
	'sibling',
	'lover',
	'parent',
	'neighbor',
	'ruler'
];

gen_data['short_document'] = [
	'letter',
	'note',
	'scroll',
	'treatise'
];

gen_data['long_document'] = [
	'journal',
	'ledger',
	'logbook',
	'tome',
	'spellbook'
];


gen_data['time_of_year'] = [
	'winter',
	'fall',
	'spring',
	'summer',
	'eclipse',
	'meteor shower',
	'solstice',
	'equinox'
]

gen_data['direction'] = [
	'above',
	'below',
	'to the left',
	'to the right',
	'behind',
	'in front'
];

gen_data['cardinal_directions'] = [
	'north',
	'south',
	'east',
	'west',
	'northeast',
	'northwest',
	'southeast',
	'southwest'
]

gen_data['number'] = [
	'two',
	'five',
	'a dozen',
	'ten',
	'fifteen',
	'one hundred'
];

gen_data['units'] = [
	'leagues',
	'kilometers',
	'valleys',
	'mountains'
];


gen_data['descriptor'] = [
	'blood-red',
	'featureless',
	'arachnid',
	'putrid'
];

gen_data['tarot_arcana'] = [
	'Magician',
	'High Priestess',
	'Empress',
	'Hierophant',
	'Lover',
	'Chariot',
	'Hermit',
	'Great Wheel',
	'Justicar',
	'Hanged Person',
	'Reaper',
	'Temperance',
	'Devil',
	'Tower',
	'Star',
	'Moon',
	'Sun',
	'Judge',
	'World',
	'Fool',
	'King',
	'Queen',
	'Knight',
	'Page'
]

gen_data['verb'] = [
	'dancing',
	'carving',
	'singing',
	'fighting',
	'sleeping',
	'eating',
	'spying',
	'harvesting',
	'running',
	'walking',
	'crawling',
	'jumping',
	'drinking'
]	

gen_data['object'] = [
	'{mundane_objects}',
	'{valuable_objects}'
];

gen_data['valuable_objects'] = [
	'{gemstone}',
	'an ingot of {metals}',
	'{weapon}',
	'{armor}'
];

gen_data['mundane_objects'] = [
	'a chair',
	'{food}',
	'a spoon'
];

gen_data['metals'] = [
'gold',
'silver',
'platinum',
'tin',
'copper',
'steel',
'bronze',
'pyrite'
];	

gen_data['gemstone'] = [
'a diamond',
'an opal',
'an emerald',
'a ruby',
'a sapphire',
'a topaz',
'a quartz crystal',
'a garnet'
];	


gen_data['food'] = [
'mushrooms',
'field greens',
'bundled herbs',
'a leg of lamb'
];

// - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
